### ISSUE TITLE
We've listed swift-mujoco

### ISSUE THREAD

**Issue by yuvaltassa** [liuliu/swift-mujoco#1]
Hi,

This is Yuval from MuJoCo development team, just a heads up that we've listed swift-mujoco in [our README](https://github.com/deepmind/mujoco#third-party-bindings), hope that's cool 🙂  

Cheers

**Comment by liuliu** [comment]
Thank you! I am waiting for your next release to catch up the version number :) (The plan is to keep version number in sync with main MuJoCo).
