### ISSUE TITLE
Support headless rendering

### ISSUE THREAD

**Issue by philipturner** [liuliu/swift-mujoco#4]
I'm trying to run [your demo](https://liuliu.me/eyes/fun-with-motion-jpeg-jupyter-notebook-and-how-to-stream-gui-and-animations-in-the-browser/) on Google Colab. I've spent about 4 hours bypassing incompatibilities, but one difficult one is GLFW. It's similar to [this](https://github.com/JuliaGL/GLFW.jl/issues/174). Setting the `DISPLAY` variable makes Colab [stall indefinitely](https://github.com/glfw/glfw/issues/734). I'm using a cloud K80 GPU which does not have a framebuffer, but supports OpenGL.

I'm going to try either (a) forking your repo to use straight OpenGL or (b) forking GLFW to support headless rendering. Perhaps you could change swift-mujoco to use OpenGL directly, so future users don't have the problem.

**Comment by liuliu** [comment]
Interesting. Yes, my use case bypassed this by setting `DISPLAY` variable. I would be interested in learning how to use headless rendering. I tried that within the GLFW context but the result is not good (I cannot remember details, something about cannot exceed some random sizes).

I think there are also some limitations on MuJoCo side with headless rendering, probably worthwhile to check their codebase to avoid any their issues.

**Comment by philipturner** [comment]
It seems `mujoco-py` supports headless rendering through EGL. That bypasses X11 and obviates the need for a `DISPLAY` variable. Have you tried that approach?

https://vedder.io/misc/mujoco_py.html

I need to get this working within the time frame of ~1 week.

**Comment by liuliu** [comment]
Yeah, I didn't looked into MuJoCo Py as that is deprecated in favor of the in-tree MuJoCo Python binding.

Ah, found it: https://github.com/deepmind/mujoco/blob/807097148e5ca5869e8b06468f53f27e705fc681/src/render/render_context.c#L1611

It hard-coded 800x600 as the offscreen render size, and there is no public API to change it.

**Comment by liuliu** [comment]
If you encountered this issue in your investigation (using headless rendering), probably open an issue in deepmind/mujoco so they can expose this as an API?

**Comment by philipturner** [comment]
Would you mind opening the issue? You seem to have more knowledge of the library, and would know what to say. Just ping me there and recognize that I found the problem first.

If I can compile a fork of MuJoCo's C library from source, using SwiftPM, I should be able to finish my project. For reference, here's the Jupyter notebook for how far I am now. Warning: it probably won't run correctly.

[Colab_Video_Streaming.ipynb.zip](https://github.com/liuliu/swift-mujoco/files/9942318/Colab_Video_Streaming.ipynb.zip)

**Comment by philipturner** [comment]
I decided MuJoCo + Colab might not be the best solution for my project, so we're no longer bound by a 1 week time constraint. Still, we should mention this issue to DeepMind.

**Comment by liuliu** [comment]
Thanks. Definitely! I was busy on another project (swift-diffusion), and will get some time back next week to update swift-mujoco to the latest (2.3.0), and raise this issue.

**Comment by philipturner** [comment]
> I was busy on another project (swift-diffusion)

Did you see the response I sent on Swift Forums about performance for swift-diffusion?

**Comment by liuliu** [comment]
> Did you see the response I sent on Swift Forums about performance for swift-diffusion?

Yes, I did, very helpful, but I also have some updates to you, that's why I haven't replied yet, it is going to be a similarly long email :)

**Comment by philipturner** [comment]
Here's a better Colab notebook to link in the issue on deepmind/mujoco:

https://drive.google.com/file/d/1euKxUxpLdvWA0HIFyg-NUiTs2fOnq8yr/view?usp=sharing
